### ISSUE TITLE
Documentation around how to integrate and use bubbleprof with an express/hapi/fastify

### ISSUE THREAD

**Issue by rgadda** [nearform/node-clinic-bubbleprof#230]
Hello,
I am trying to integrate bubbleprof, doctor and flame with one of my projects and I am failing to understand how I can integrate them with express, hapi or fastify framework and use it. Can you please improve the documentation with some example. I have gone through the example repo for bubbleprof and couldn't connect the dot's.

Thanks
Rajiv

**Comment by rgadda** [comment]
Just to give more context and info:
When I am following example related bubbleprof for https://github.com/nearform/node-clinic-bubbleprof-examples/tree/master/server-side-rendering I am getting below error:

```
➜  server-side-rendering git:(master) ✗ clinic bubbleprof -- node src/server
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/Users/rajiv.gadda/Documents/Workspace/personal/clinicjs/node-clinic-bubbleprof-examples/server-side-rendering/src/server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at getMainDirectory (/usr/local/lib/node_modules/clinic/node_modules/@nearform/bubbleprof/collect/system-info.js:19:14)
    at systemInfo (/usr/local/lib/node_modules/clinic/node_modules/@nearform/bubbleprof/collect/system-info.js:33:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/clinic/node_modules/@nearform/bubbleprof/injects/logger.js:15:55)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
/usr/local/lib/node_modules/clinic/bin.js:237
      if (err) throw err
               ^

Error: process exited by signal SIGSEGV
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/clinic/node_modules/@nearform/bubbleprof/index.js:80:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

**Comment by AlanSl** [comment]
Hi rgadda, thanks for posting this issue, I've looked into it and found that the how-to docs appear to be slightly out of date. Where it says:

```
clinic bubbleprof -- node src/server
```

...try instead this:

```
clinic bubbleprof -- node server
```

Also, the docs could be clearer that you should have a second console window open, navigated to `node-clinic-bubbleprof-examples`. Then while the first window keeps the server running, you run `node server-side-rendering/stories.js` in the _second_ window - then when that command finishes in the second window, `ctrl-c` in the first window to shut down the server and generate the profile.

I'll put in a quick PR to update those docs.

**Comment by AlanSl** [comment]
As for the first more general question - you don't need to do anything special to integrate with Express, Hapi, Fastify etc - so long as your application is listening on a port, you just run your application with `clinic bubbleprof --` before your usual start command e.g. `clinic bubbleprof -- node some-script.js` then just fire requests at that port. 

We recommend autocannon and using the `--on-port` flag like this to automatically point it at your application's port. Just replace `some-script` with the normal way you start your application listening for requests:

```
clinic bubbleprof --on-port 'autocannon http://localhost:$PORT' -- node some-script.js
```

Probably the best place to start, though, is Matteo Collina's demo video on https://clinicjs.org/ which shows an example end to end workflow using the whole Clinic suite. If you haven't already seen it I think this will help with the big-picture "how are these tools intended to be used?" question.

**Comment by rgadda** [comment]
@AlanSl the above-updated commands work. thank you for your prompt response. I will try to run it for my application and update you in a bit. Thank you once again. I am really impressed with clinicjs and eager to use it 😄

**Comment by AlanSl** [comment]
Resolved in https://github.com/nearform/node-clinic-bubbleprof-examples/pull/6
