### ISSUE TITLE
Cannot read property 'name' of null

### ISSUE THREAD

**Issue by SeanSobey** [nearform/node-clinic-bubbleprof#303]
I am getting the above error using the programmatic API, it is failing in the `visualize` step (`visualizeAsync` in my code), full stack trace:
```
TypeError: Cannot read property 'name' of null
    at MarkModuleAggregateNodes._transform (\App\node_modules\@nearform\bubbleprof\analysis\aggregate\mark-module-aggregate-nodes.js:21:45)
    at MarkModuleAggregateNodes.Transform._read (_stream_transform.js:190:10)
    at MarkModuleAggregateNodes.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at MarkModuleAggregateNodes.Writable.write (_stream_writable.js:294:11)
    at MarkPartyAggregateNodes.ondata (_stream_readable.js:666:20)
    at MarkPartyAggregateNodes.emit (events.js:182:13)
    at MarkPartyAggregateNodes.EventEmitter.emit (domain.js:459:23)
    at addChunk (_stream_readable.js:283:12)
```

```js
async function reportClinicBubbleProf() {

	const fs = require('fs');
	const log = require('fancy-log');
	const ClinicBubbleprof = require('@nearform/bubbleprof');
	const mkdirpAsync = util.promisify(require('mkdirp'));

	const flame = new ClinicBubbleprof({
	});
	const collectAsync = util.promisify(flame.collect.bind(flame));
	const visualizeAsync = util.promisify(flame.visualize.bind(flame));

	log('Running tests to collect data');
	const reportName = await collectAsync(['node', path.join('node_modules', 'gulp', 'bin', 'gulp.js'), 'test']);
	const clinicFolderPath = path.join(clinicPath, reportName);
	await mkdirpAsync(clinicPath);
	await fs.promises.rename(reportName, clinicFolderPath);
	log('Analyzing data');
	const clinicReportFolderPath = path.join(clinicReportPath, 'bubbleprof');
	await mkdirpAsync(clinicReportFolderPath);
	const clinicReportFileName = path.join(clinicReportFolderPath, reportName) + '.html';
	await visualizeAsync(clinicFolderPath, clinicReportFileName);
	log(`Saved report at '${clinicReportFileName}.html'`);
}
gulp.task('report:clinic:bubbleprof', reportClinicBubbleProf);
```
I am working on a windows 10 PC, Node v0.15.0.

The same code works with the Flame and Doctor apis

**Comment by goto-bus-stop** [comment]
Hi! This is almost certainly a bug, but I'm not having much luck reproducing it yet.

Does it still happen if you run the tests without gulp, if possible? Eg if you're using mocha, try calling `collectAsync` on the mocha CLI instead of gulp.

Similarly, could you share an as-small-as-possible test file that reproduces the problem? that may not be possible if the problem goes away on a smaller program, but it'd be really helpful.

(I can sorta see where it's going wrong from reading the code, but I'm not sure how and when it ends up in that situation, so I'm struggling to create a test case!)

**Comment by goto-bus-stop** [comment]
that looks useful! yes, if you could also upload the generated files that would be great too :)
