### ISSUE TITLE
bubbleprof breaks on Next.js codebase

### ISSUE THREAD

**Issue by timneutkens** [nearform/node-clinic-bubbleprof#371]
When trying to run `clinic bubbleprof -- node node_modules/.bin/next build test/integration/production` on the Next.js codebase an error happens:

```js
SyntaxError: Unexpected token  in JSON at position 1
    at JSON.parse (<anonymous>)
    at Parser._transform (/Users/timneutkens/.config/yarn/global/node_modules/@nearform/trace-events-parser/index.js:41:34)
    at Parser.Transform._read (_stream_transform.js:191:10)
    at Parser.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Parser.Writable.write (_stream_writable.js:318:11)
    at TraceEventDecoder._transform (/Users/timneutkens/.config/yarn/global/node_modules/@nearform/bubbleprof/format/trace-event-decoder.js:62:17)
    at TraceEventDecoder.Transform._read (_stream_transform.js:191:10)
    at TraceEventDecoder.Transform._write (_stream_transform.js:179:12)
```

## To reproduce

- Clone https://github.com/vercel/next.js
- Run `yarn` (we use workspaces)
- Run `clinic bubbleprof -- node node_modules/.bin/next build test/integration/production`

**Comment by simoneb** [comment]
@timneutkens is this issue solved?

**Comment by timneutkens** [comment]
No, just cleaned up my open issues last week as I don't want people to spend time on things that we're not actively using 👍 This is however still a bug in bubbleprof for sure 👍
